version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region sa-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t front-docker .
      - docker tag front-docker 452359159316.dkr.ecr.sa-east-1.amazonaws.com/front-docker
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 452359159316.dkr.ecr.sa-east-1.amazonaws.com/front-docker
