version: '3'
services: 
  ui: 
    build: 
      context: .
    container_name: ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-ui
    ports: 
      - "4200:4200"
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx
    ports: 
      - "80:80"
